version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 8
    groups:
      production-patch-minor:
        dependency-type: production
        update-types:
          - patch
          - minor
      development-patch-minor:
        dependency-type: development
        update-types:
          - patch
          - minor
